platform :ios, '9.0'

target 'AwesomeProject' do
  # Pods for AwesomeProject
  pod 'AppCenterReactNativeShared', '~> 1.5.1'
    
    pod 'AppCenter/Analytics', '~> 1.6.1'
    pod 'AppCenter/Crashes', '~> 1.6.1'
  platform :ios, '9.0'
  target 'AwesomeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  end

  target 'AwesomeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject-tvOS


end
